name: Deploy Website with Docker

on: push

jobs: 
    deploy:
        runs-on: ubuntu-latest
        
        steps:
            - name: Checkout
              uses: actions/checkout@v7

            - name: ssh setup
              run: |
                  mkdir -p ~/.ssh
                  echo "${{secrets.SSH_PRIVATE_KEY}}" > ~/.ssh/mein_schlüssel
                  chmod 600 ~/.ssh/mein_schlüssel
                  ssh-keyscan -H ${{secrets.EC2_IP}} >> ~/.ssh/known_hosts

            - name: install docker on ec2
              run: |
                  ssh -i ~/.ssh/mein_schlüssel ubuntu@${{secrets.EC2_IP}} "sudo apt update && sudo apt install docker.io -y"
                  ssh -i ~/.ssh/mein_schlüssel ubuntu@${{secrets.EC2_IP}} "sudo usermod -aG docker ubuntu"
              
            - name: start frontend container on ec2
              run: |
                  scp -i ~/.ssh/mein_schlüssel -r Frontend ubuntu@${{secrets.EC2_IP}}:/home/ubuntu/
                  ssh -i ~/.ssh/mein_schlüssel ubuntu@${{secrets.EC2_IP}} "docker build -t suheibs-frontend-image /home/ubuntu/Frontend"
                  ssh -i ~/.ssh/mein_schlüssel ubuntu@${{secrets.EC2_IP}} "docker stop suheibs-frontend-container || true"
                  ssh -i ~/.ssh/mein_schlüssel ubuntu@${{secrets.EC2_IP}} "docker rm suheibs-frontend-container || true"
                  ssh -i ~/.ssh/mein_schlüssel ubuntu@${{secrets.EC2_IP}} "docker run -d -p 80:80 --name suheibs-frontend-container suheibs-frontend-image"
                  

            