name: Taschenrecher Deploy Workflow

on: workflow_dispatch
jobs:
    test:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v7

            - name: install node
              uses: actions/setup-node@v6
              with:
                node-version: "20"

            - name: install dependencies && test
              run: | 
                cd testing-example
                npm install
                npm test
    
    deploy:
        runs-on: ubuntu-latest
        needs: test
        steps:
            - name: Checkout
              uses: actions/checkout@v7

            - name: ssh setup
              run: |
                  mkdir -p ~/.ssh
                  echo "${{secrets.SSH_PRIVATE_KEY}}" > ~/.ssh/mein_schlüssel
                  chmod 600 ~/.ssh/mein_schlüssel
                  ssh-keyscan -H ${{secrets.EC2_IP}} >> ~/.ssh/known_hosts

            - name: copy math.js to ec2
              run: |
                  scp -i ~/.ssh/mein_schlüssel testing-example/math.js ubuntu@${{secrets.EC2_IP}}:/home/ubuntu/math.js
           
    